provider:
  name: faas
  gateway: http://127.0.0.1:8080
  network: func_functions

functions:
  guestbook:
    lang: dockerfile
    handler: ./guestbook
    image: alexellis2/openfaas-sinatra-guestbook:0.1
    labels:
      com.openfaas.scale.min: 2
      com.openfaas.scale.max: 4
      com.openfaas.scale.zero: false
    environment_file:
      - sql.yml
